meshiterro/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  resources :post_images, only: [:new, :create, :index, :show, :destroy] do
    resource :favorites, only: [:create, :destroy]
    
    resources :post_comments,only: [:create, :destroy]
  end 
  
end

meshiterro/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

meshiterro/app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_image 
  
end

meshiterro/app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  belongs_to :user
  belongs_to :post_image
  
end

meshiterro/app/models/post_image.rb
class PostImage < ApplicationRecord
  
  belongs_to :user
  attachment :image
  has_many :post_comments, dependent: :destroy 
  has_many :favorites, dependent: :destroy
  
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end 
  
  
end

meshiterro/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :post_images, dependent: :destroy
  has_many :post_comments,dependent: :destroy
  has_many :favorites, dependent: :destroy
end

meshiterro/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    post_images_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

meshiterro/app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
    
  end 
  
  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
    
  end 
  
  
  
end

meshiterro/app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end 
end

meshiterro/app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  
  def create
    post_image = PostImage.find(params[:post_image_id])
    comment = PostComment.new(post_comment_params)
    comment.user_id = current_user.id
    comment.post_image_id = post_image.id
    comment.save
    redirect_to post_image_path(post_image)
  end 
  
  def destroy
    PostComment.find_by(id: params[:id], post_image_id: params[:post_image_id]).destroy
    redirect_to post_image_path(params[:post_image_id])
  end 
  
  private
  
  def post_comment_params
    params.require(:post_comment).permit(:comment)
  end 
    
end

meshiterro/app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController
  
  def new
    @post_image = PostImage.new
  end 
  
  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    @post_image.save
    redirect_to post_images_path
    
  end 
  
  def index
    @post_images = PostImage.page(params[:page]).reverse_order
  end 
  
  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
  end 
  
  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end 
  
  private
  
  def post_image_params
    params.require(:post_image).permit(:shop_name, :image, :caption)
  end 
  
  
end

meshiterro/app/helpers/application_helper.rb
module ApplicationHelper
end

meshiterro/app/helpers/favorites_helper.rb
module FavoritesHelper
end

meshiterro/app/helpers/homes_helper.rb
module HomesHelper
end

meshiterro/app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

meshiterro/app/helpers/post_images_helper.rb
module PostImagesHelper
end

meshiterro/app/views/homes/top.html.erb
<h1>トップページ</h1>

meshiterro/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Meshiterro</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if user_signed_in? %>
      <li>
        <%= link_to '投稿フォーム', new_post_image_path %>
      </li>
      
      <li>
        <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
      </li>
    <% else %>
      <li>
        <%= link_to "新規登録", new_user_registration_path %>
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path %>
      </li>
    <% end %>
    
    
    <%= yield %>
  </body>
</html>

meshiterro/app/views/post_images/index.html.erb
<%= @post_images.each do |post_image| %>
<div>
  <%= link_to post_image_path(post_image.id) do %>
    <%= attachment_image_tag post_image, :image %>
  <% end %>

  <p>投稿ユーザー画像:<%= image_tag('sample-author1.jpg') %></p>
  <p>ショップ名:<%= post_image.shop_name %></p>
  <p>説明:<%= post_image.caption %></p>
  <p>ユーザーネーム:<%= post_image.user.name %></p>
  <p><%= link_to "#{post_image.post_comments.count}コメント", post_image_path(post_image.id) %></p>
</div>
<% end %>
<%= paginate @post_images %>

meshiterro/app/views/post_images/new.html.erb
<h1>画像投稿フォーム</h1>
<%= form_with model:@post_image, local: true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
  <h4>ショップ名</h4>
  <%= f.text_field :shop_name %>
  <h4>説明</h4>
  <%= f.text_area :caption %>
  <%= f.submit '投稿' %>
<% end %>

meshiterro/app/views/post_images/show.html.erb
<div class="post-body">
  <%= attachment_image_tag @post_image, :image %>
  <p>ショップ名:<%= @post_image.shop_name %></p>
  <p>説明:<%= @post_image.caption %></p>
  <p>ユーザーネーム:<%= @post_image.user.name %></p>
  <p>投稿日時:<%= @post_image.created_at.strftime('%Y/%m/%d') %></p>
  <% if @post_image.user == current_user %>
    <%= link_to '削除', post_image_path(@post_image), method: :delete %>
  <% end %>
  <% if @post_image.favorited_by?(current_user) %>
  
    <p>
      <%= link_to post_image_favorites_path(@post_image),method: :delete do %>
        ❤<%= @post_image.favorites.count %>いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
       ♡<%= @post_image.favorites.count %>いいね
      <% end %>
    </p>
  <% end %>
</div>

<div class="comments">
<p>コメント件数:<%= @post_image.post_comments.count %></p>
<% @post_image.post_comments.each do |post_comment| %>
  <p><%= image_tag('sample-author1.jpg') %></p>
  <%= post_comment.user.name %>
  <%= post_comment.created_at.strftime('%Y/%m/%d') %><%= post_comment.comment %>
  <% if post_comment.user == current_user %>
  <div class="comment-delete">
    <%= link_to '削除',post_image_post_comment_path(post_comment.post_image, post_comment),method: :delete %>
  </div>
  <% end %>

<% end %>
</div>

<div class="new-comment">
<%= form_with(model:[@post_image,@post_comment], local: true) do |f| %>
  <%= f.text_area :comment,row:'5',placeholder: "コメントをここに" %>
  <%= f.submit "送信する" %>
<% end %>
</div>